name: Build VSIX

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build VSIX
        run: npx @vscode/vsce package

      - name: Upload VSIX
        uses: actions/upload-artifact@v4
        with:
          name: tab-police-${{ github.ref_name }}.vsix
          path: tab-police-*.vsix

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: tab-police-*.vsix
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}